---
language: node_js

node_js:
  - 8.15.1

branches:
  only:
    - master

integrations:
  hub:
    - integrationName: docker-registry
      type: dockerRegistryLogin

env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/test
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - DOCKER_REPO="meetup-assembly-lines"
    - DOCKER_ACC=lowbit
    - SHIP_IMG_RES=$DOCKER_REPO"_img_dh"

build:
  ci:
    - npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    # - npm test
    - $MOD_LOC/mocha --exit --recursive "$TESTS_LOC_DIR/http.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    # - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    # - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    # - popd
  post_ci:
    - docker build -t $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER .
    - docker push $DOCKER_ACC/$DOCKER_REPO:$BRANCH.$BUILD_NUMBER
  on_success:
    - shipctl put_resource_state $SHIP_IMG_RES versionName $BRANCH.$BUILD_NUMBER

resources:
  - name: meetup-assembly-lines_img_dh
    type: image
    integration: docker-registry
    versionTemplate:
      sourceName: "lowbit/meetup-assembly-lines" # replace with your Hub URL
      isPull: false
      versionName: latest

jobs:
  - name: meetup-app-dev_runCI
    type: runCI
    steps:
      - OUT: node_app_img_dh
